const intro=document.getElementById("intro");const enterBtn=document.getElementById("enterBtn");const music=document.getElementById("birthdayMusic");const musicBtn=document.getElementById("musicBtn");const particles=document.getElementById("particles");const balloons=document.getElementById("balloons");const maskButton=document.getElementById("maskButton");const surpriseModal=document.getElementById("surpriseModal");const closeSurprise=document.getElementById("closeSurprise");music.volume=.45;let websiteStarted=false;
enterBtn.addEventListener("click",async()=>{if(websiteStarted)return;websiteStarted=true;intro.classList.add("hide");try{await music.play();musicBtn.textContent="🔊"}catch(error){musicBtn.textContent="🔇"}createParticles();startBalloons();comicExplosion(innerWidth/2,innerHeight/2,"THWIP!")});
musicBtn.addEventListener("click",()=>{if(music.paused){music.play();musicBtn.textContent="🔊"}else{music.pause();musicBtn.textContent="🔇"}});
function createParticles(){for(let i=0;i<80;i++){const p=document.createElement("span");p.className="particle";p.style.left=Math.random()*100+"%";p.style.animationDuration=5+Math.random()*12+"s";p.style.animationDelay=Math.random()*10+"s";p.style.transform=`scale(${.5+Math.random()})`;particles.appendChild(p)}}
const balloonColors=["#e50914","#0754c7","#ffd400","#1683ff","#ff3b30"];
function createBalloon(){const b=document.createElement("div");b.className="balloon";const c=balloonColors[Math.floor(Math.random()*balloonColors.length)];b.style.background=c;b.style.color=c;b.style.left=Math.random()*100+"%";b.style.animationDuration=7+Math.random()*7+"s";b.style.transform=`scale(${.7+Math.random()*.7})`;balloons.appendChild(b);setTimeout(()=>b.remove(),15000)}
function startBalloons(){setInterval(createBalloon,900)}
const comicWords=["POW!","BAM!","BOOM!","THWIP!","WHAM!","ZAP!"];
function comicExplosion(x,y,customWord=null){const e=document.createElement("div");e.className="comic-effect";e.textContent=customWord||comicWords[Math.floor(Math.random()*comicWords.length)];e.style.left=x+"px";e.style.top=y+"px";document.body.appendChild(e);setTimeout(()=>e.remove(),850)}
setInterval(()=>{if(!websiteStarted)return;comicExplosion(10+Math.random()*(innerWidth-20),10+Math.random()*(innerHeight-20))},4500);
document.addEventListener("click",event=>{if(!websiteStarted)return;if(event.target.closest(".music-btn")||event.target.closest(".mask-button"))return;shootWeb(event.clientX,event.clientY)});
function shootWeb(targetX,targetY){const startX=innerWidth/2,startY=innerHeight-40,dx=targetX-startX,dy=targetY-startY,distance=Math.sqrt(dx*dx+dy*dy),angle=Math.atan2(dy,dx)*180/Math.PI;const web=document.createElement("div");web.className="web-shot";web.style.left=startX+"px";web.style.top=startY+"px";web.style.width=distance+"px";web.style.transform=`rotate(${angle}deg)`;document.body.appendChild(web);setTimeout(()=>web.remove(),400);setTimeout(()=>comicExplosion(targetX,targetY),250)}
maskButton.addEventListener("click",openSurprise);
function openSurprise(){surpriseModal.classList.add("show");document.body.style.overflow="hidden";comicExplosion(innerWidth/2,innerHeight/2,"BOOM!");createConfetti(120)}
closeSurprise.addEventListener("click",closeSurpriseModal);surpriseModal.addEventListener("click",event=>{if(event.target.classList.contains("surprise-backdrop"))closeSurpriseModal()});function closeSurpriseModal(){surpriseModal.classList.remove("show");document.body.style.overflow=""}
document.addEventListener("keydown",event=>{if(event.key==="Escape"&&surpriseModal.classList.contains("show"))closeSurpriseModal()});
function createConfetti(amount){const colors=["#e50914","#0754c7","#ffd400","#fff","#1683ff"];for(let i=0;i<amount;i++){const p=document.createElement("div");p.className="confetti";p.style.left=Math.random()*100+"%";p.style.background=colors[Math.floor(Math.random()*colors.length)];p.style.animationDuration=2+Math.random()*3+"s";p.style.animationDelay=Math.random()*1.5+"s";p.style.transform=`rotate(${Math.random()*360}deg)`;document.body.appendChild(p);setTimeout(()=>p.remove(),5500)}}
const flame=document.getElementById("flame");const cake=document.getElementById("cake");cake.addEventListener("click",()=>{if(!flame)return;flame.style.opacity="0";comicExplosion(innerWidth/2,innerHeight/2,"POOF!");createConfetti(50);setTimeout(()=>flame.style.opacity="1",3000)});
let lastScroll=0;window.addEventListener("scroll",()=>{const current=scrollY;if(Math.abs(current-lastScroll)>350){const words=["SWOOSH!","WHOOSH!","THWIP!"];comicExplosion(innerWidth*.8,innerHeight*.2,words[Math.floor(Math.random()*words.length)]);lastScroll=current}});
let mouseTimer;document.addEventListener("mousemove",event=>{if(!websiteStarted)return;clearTimeout(mouseTimer);mouseTimer=setTimeout(()=>{const dot=document.createElement("div");dot.style.position="fixed";dot.style.left=event.clientX+"px";dot.style.top=event.clientY+"px";dot.style.width="5px";dot.style.height="5px";dot.style.borderRadius="50%";dot.style.background="white";dot.style.boxShadow="0 0 10px white";dot.style.pointerEvents="none";dot.style.zIndex="99996";document.body.appendChild(dot);dot.animate([{opacity:1,transform:"scale(1)"},{opacity:0,transform:"scale(0)"}],{duration:500});setTimeout(()=>dot.remove(),500)},40)});
